env:
- GKE_cluster_name="my-first-cluster-1"
- GKE_zone="us-central1-c"
- GKE_project_id="k8ss-281906"

before_script:
- export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash
  
script:
- source ${HOME}/google-cloud-sdk/path.bash.inc
- echo "$GCLOUD_SERVICE_KEY_STG" | base64 --decode > ${HOME}/gcloud-service-key.json
- gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
- gcloud components install kubectl
- gcloud container clusters get-credentials $GKE_cluster_name --zone $GKE_zone --project $GKE_project_id
- kubectl get nodes

