---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizapp
  labels:
    app: quizapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizapp
  template:
    metadata:
      labels:
        app: quizapp
    spec:
      containers:
        - name: quizapp
          image: gcr.io/k8ss-281906/quizapp:latest

---

apiVersion: v1
kind: Service
metadata:
  name: quizapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: quizapp
